name: CI
on:
  push:
    branches: [ "Hexo-Solitude" ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: 自动部署Hexo
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: Hexo-Solitude

      - name: 安装 Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.x"

      - name: 安装 Hexo
        run: |
          npm install hexo-cli -g --save

      - name: 缓存 node-modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 安装项目依赖
        # if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm install --save

      - name: 配置环境
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "1226594277@qq.com"
          git config --global user.name "MskTmi"
          ssh-keygen -y -f ~/.ssh/id_rsa
      
      - name: 清理缓存
        run: |
          hexo clean
       
      - name: 更新 Algolia 索引
        run: |
          sed -i 's/ALGOLIA_WRITE_API_KEY/${{ secrets.ALGOLIA_WRITE_API_KEY }}/' ./_config.solitude.yml
          hexo algolia

      - name: 更新追番追剧
        run: |
          hexo bangumi -u
          hexo cinem -u

      - name: 部署 Hexo 
        run: |
          hexo d